// import { useContext, useState } from "react";
// import { CounterContext } from "../App";



// function Counter(){

//     //WE REMOVE THE USESTATE CODE OR LIFT FROM THIS TO TO PARENT WHERE IT CAN BE ACCESSIBLE BY OTHER COMPONENT ALSO

//     const {counter, setCounter} =useContext(CounterContext)

//     return (
//     <>
//     <h1>Counter is : {counter}</h1>
//     <button onClick={()=> setCounter(counter=>counter+1)}>Increment</button>
//     <button onClick={()=> setCounter(counter=>counter-1)}>Decrement</button>
//     </>
//     )

// }

// export default Counter;
//THIS PROCESS OF LIFTING THE STATE TO THE MAIN COMMON PARENT IS CALLED STATE LIFTING
//AND THE PROCESS OF SENDING THE PROP THROUGH EVERY CHILD COMPONENT IS CALLED PROP DRILING



//AND THE PROBLEM OCCURS BECAUSE OF PASSING THE PROP TO EVERY CHILD WHO DONT NEED IT ALSO RE RENDER WHENEVER THE VALUE OF STATE IS CHANGE
//SO TO REMOVE THE UNNESSARY RE RENDER BCZ OF PROP DRILING IS REMOVE MY USING USECONTEXT PROP


//USE CONTEXT HOOK---> THIS CREATE CONTEXT FOR US 
// IT IS PRODUCER AND A CONSUMER IS CREATED IT SAYS I AM CREATING A STATE COUNT AND STATE VARIABLE JISE ISE USE KAR NA HAI USE USE KAR LENA USING USECONTEXT

//IT HELP US FROM PROP DRILING CONSUMER RECIVE AND CONSUME THE PRODUCT CREATED BY USE CONTEXT