
import Display from "./Display";

function Header({counter}){

    return (
    <>
    <h1>I am header component</h1>
    <Display counter={counter}/>
    </>
    )
    

}

export default Header;
//THIS PROCESS OF LIFTING THE STATE TO THE MAIN COMMON PARENT IS CALLED STATE LIFTING
//AND THE PROCESS OF SENDING THE PROP THROUGH EVERY CHILD COMPONENT IS CALLED PROP DRILING



//AND THE PROBLEM OCCURS BECAUSE OF PASSING THE PROP TO EVERY CHILD WHO DONT NEED IT ALSO RE RENDER WHENEVER THE VALUE OF STATE IS CHANGE
//SO TO REMOVE THE UNNESSARY RE RENDER BCZ OF PROP DRILING IS REMOVE MY USING USECONTEXT PROP

//USE CONTEXT HOOK---> THIS CREATE CONTEXT FOR US 
// IT IS PRODUCER AND A CONSUMER IS CREATED IT SAYS I AM CREATING A STATE COUNT AND STATE VARIABLE JISE ISE USE KAR NA HAI USE USE KAR LENA USING USECONTEXT

//IT HELP US FROM PROP DRILING CONSUMER RECIVE AND CONSUME THE PRODUCT CREATED BY USE CONTEXT